package com.limepak.app;

import android.app.Application;
import android.content.Context;

import com.getcapacitor.Bridge;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;

import java.util.List;

/**
 * LIMEPAK Android Main Application
 * Generated by Capacitor
 */
public class MainApplication extends Application {
    
    private Bridge bridge;
    
    @Override
    public void onCreate() {
        super.onCreate();
        
        // Initialize Capacitor
        this.initializeBridge();
    }
    
    private void initializeBridge() {
        // Create the bridge
        this.bridge = new Bridge(this);
        
        // Register plugins
        this.registerPlugins();
        
        // Initialize the bridge
        this.bridge.init();
    }
    
    private void registerPlugins() {
        // Get the list of plugins from the bridge configuration
        List<Class<? extends Plugin>> pluginClasses = this.bridge.getPluginClasses();
        
        for (Class<? extends Plugin> pluginClass : pluginClasses) {
            try {
                Plugin plugin = pluginClass.getDeclaredConstructor().newInstance();
                this.bridge.addPlugin(plugin);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    public Bridge getBridge() {
        return this.bridge;
    }
    
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
    }
}
