package com.limepak.app;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;
import java.util.List;

/**
 * LIMEPAK Android Main Activity
 * Generated by Capacitor
 */
public class MainActivity extends BridgeActivity {
    
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // Initial load of the web app
        this.load();
    }
    
    @Override
    public List<Class<? extends Plugin>> getPluginClasses() {
        // Return list of plugin classes
        List<Class<? extends Plugin>> pluginClasses = new ArrayList<>();
        return pluginClasses;
    }
    
    @Override
    public void onDestroy() {
        super.onDestroy();
    }
}
