"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import { Confirm } from "@/components/ui/confirm";
import { Menu, type MenuEntry } from "@/components/ui/menu";
import { Chip } from "@/components/ui/misc";
import { exportSingleLayer } from "@/lib/state/data";
import { useStore } from "@/lib/state/provider";
import type { LayerSummary } from "@/lib/types";
import { LayerIcon } from "@/lib/workspace/icons";
import { miniLayout } from "@/lib/workspace/geometry";
import { cn } from "@/lib/utils/cn";
import { formatRelativeTime, pluralize } from "@/lib/utils/format";

/**
 * A Layer, recognised at a glance: what it is, how full it is, when you last
 * looked, and — in the faint thumbnail — the actual spatial arrangement you left
 * behind. That preview is derived from real card positions, not decoration.
 */
export function LayerCard({ summary }: { summary: LayerSummary }) {
  const store = useStore();
  const router = useRouter();
  const { layer, cardCount, tasksTotal, tasksDone, kindCounts } = summary;
  const [confirming, setConfirming] = useState(false);
  const preview = miniLayout(summary.cards);
  const open = () => {
    store.openLayer(layer.id);
    router.push(`/layers/${layer.id}`);
  };

  const entries: MenuEntry[] = [
    { label: "Layer details", onSelect: () => store.setLayerDialog({ mode: "edit", layerId: layer.id }) },
    {
      label: "Duplicate",
      onSelect: () => {
        void store.duplicateLayer(layer.id).then((copy) => {
          if (copy) store.notify(`Duplicated as “${copy.name}”.`, { tone: "success" });
        });
      },
    },
    { label: "Export this Layer", onSelect: () => void exportSingleLayer(store, layer) },
    { type: "separator" },
    { label: "Delete Layer", tone: "danger", onSelect: () => setConfirming(true) },
  ];

  return (
    <>
      <article
        data-accent={layer.accent ?? "slate"}
        data-layer-card={layer.id}
        className={cn(
          "group relative flex min-h-[148px] flex-col overflow-hidden rounded-panel border border-line bg-surface",
          "shadow-plate transition-[transform,box-shadow,border-color] duration-200 ease-out",
          "hover:-translate-y-[1px] hover:border-line-strong hover:shadow-lift",
        )}
      >
        <span className="accent-edge absolute inset-x-0 top-0 h-[2px] opacity-70" aria-hidden />
        <button
          type="button"
          onClick={open}
          className="flex min-h-0 flex-1 flex-col items-start gap-2 px-4 pb-3 pt-3.5 text-left"
          aria-label={`Open Layer ${layer.name}`}
        >
          <span className="flex w-full items-start gap-2.5">
            <span className="accent-soft grid h-8 w-8 shrink-0 place-items-center rounded-[9px]">
              <LayerIcon icon={layer.icon} size={15} strokeWidth={1.9} />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block truncate text-[14.5px] font-semibold tracking-[-0.01em] text-ink">{layer.name}</span>
              {layer.description ? (
                <span className="mt-0.5 block truncate text-[12px] leading-snug text-muted">{layer.description}</span>
              ) : null}
            </span>
          </span>

          <span className="relative mt-auto block h-[42px] w-full overflow-hidden rounded-[6px] border border-line/70 bg-surface-2">
            {preview.length === 0 ? (
              <span className="grid h-full place-items-center text-[10.5px] text-faint">Empty canvas</span>
            ) : (
              preview.map((rect, index) => (
                <span
                  key={index}
                  aria-hidden
                  className="absolute rounded-[2px] bg-[color-mix(in_srgb,rgb(var(--accent-rgb))_38%,transparent)]"
                  style={{
                    left: `${rect.x * 100}%`,
                    top: `${rect.y * 100}%`,
                    width: `${Math.min(rect.w, 0.42) * 100}%`,
                    height: `${Math.min(rect.h, 0.5) * 100}%`,
                  }}
                />
              ))
            )}
          </span>
        </button>

        <footer className="flex items-center gap-2 border-t border-line/70 px-4 py-2 text-[11px] text-faint">
          <span className="font-mono tabular-nums">{cardCount}</span>
          <span aria-hidden>·</span>
          {tasksTotal > 0 ? (
            <span className="text-muted">
              {tasksDone}/{tasksTotal} done
            </span>
          ) : (
            <span>{kindSummary(kindCounts)}</span>
          )}
          {layer.metadata?.demo === true ? (
            <Chip tone="accent" className="ml-0.5" title="Generated by “Try an example”">
              Sample
            </Chip>
          ) : null}
          <span className="ml-auto whitespace-nowrap">Last opened {formatRelativeTime(layer.lastOpenedAt)}</span>
          <Menu
            label={`Actions for ${layer.name}`}
            align="end"
            entries={entries}
            className="shrink-0"
            trigger={({ toggle, open: menuOpen, id }) => (
              <button
                id={id}
                type="button"
                aria-label={`Actions for ${layer.name}`}
                aria-haspopup="menu"
                aria-expanded={menuOpen}
                onClick={toggle}
                className={cn(
                  "-mr-1 grid h-6 w-6 place-items-center rounded-md text-faint transition-all",
                  "hover:bg-surface-3 hover:text-ink focus-visible:opacity-100",
                  menuOpen ? "opacity-100" : "opacity-0 group-hover:opacity-100",
                )}
              >
                <svg viewBox="0 0 16 16" width="13" height="13" fill="currentColor" aria-hidden>
                  <circle cx="3.5" cy="8" r="1.3" />
                  <circle cx="8" cy="8" r="1.3" />
                  <circle cx="12.5" cy="8" r="1.3" />
                </svg>
              </button>
            )}
          />
        </footer>
      </article>

      <Confirm
        open={confirming}
        tone="danger"
        title={`Delete “${layer.name}”?`}
        confirmLabel="Delete Layer"
        body={`This removes the Layer and ${pluralize(cardCount, "card")} from local storage. Export it first if you want a copy.`}
        onCancel={() => setConfirming(false)}
        onConfirm={() => {
          setConfirming(false);
          void store.deleteLayer(layer.id);
        }}
      />
    </>
  );
}

function kindSummary(counts: Record<string, number | undefined>): string {
  const parts = Object.entries(counts)
    .filter(([, value]) => (value ?? 0) > 0)
    .map(([kind, value]) => `${value} ${kind}${value === 1 ? "" : "s"}`);
  return parts.length > 0 ? parts.slice(0, 3).join(" · ") : "No cards yet";
}

export function NewLayerTile({ onCreate, compact = false }: { onCreate: () => void; compact?: boolean }) {
  return (
    <button
      type="button"
      onClick={onCreate}
      className={cn(
        "group flex min-h-[148px] flex-col items-center justify-center gap-2 rounded-panel border border-dashed border-line-strong",
        "bg-transparent text-faint transition-all duration-200",
        "hover:border-[color-mix(in_srgb,var(--accent)_55%,var(--line-strong))] hover:bg-surface hover:text-ink",
        compact ? "min-h-[92px]" : "",
      )}
    >
      <span className="grid h-9 w-9 place-items-center rounded-full border border-line bg-surface-2 transition-transform duration-200 group-hover:scale-105">
        <svg viewBox="0 0 16 16" width="15" height="15" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden>
          <path d="M8 3.5v9M3.5 8h9" strokeLinecap="round" />
        </svg>
      </span>
      <span className="text-[13px] font-medium">New Layer</span>
      <span className="text-[11px] text-faint opacity-0 transition-opacity group-hover:opacity-100">
        One thing you are doing
      </span>
    </button>
  );
}
