export type ViewMode = "canvas" | "list";

export type LayerViewport = {
  x: number;
  y: number;
  scale: number;
  mode: ViewMode;
};

export type Layer = {
  id: string;
  name: string;
  description?: string;
  /** Key into LAYER_ICONS (see lib/workspace/icons.ts). */
  icon?: string;
  /** Key into ACCENTS (see lib/workspace/icons.ts). */
  accent?: string;
  createdAt: number;
  updatedAt: number;
  lastOpenedAt?: number;
  viewport?: LayerViewport;
  metadata: LayerMetadata;
};

export type LayerMetadata = {
  /** True when the Layer was generated by "Try an example". */
  demo?: boolean;
  source?: "manual" | "demo" | "import";
  [key: string]: unknown;
};

export type NewLayer = {
  name: string;
  description?: string;
  icon?: string;
  accent?: string;
  metadata?: LayerMetadata;
};

export type LayerSummary = {
  layer: Layer;
  /** The Layer's cards, in canvas order — the preview needs their positions. */
  cards: import("./card").Card[];
  cardCount: number;
  tasksTotal: number;
  tasksDone: number;
  /** "note · 3, task · 2 …" style breakdown for the list card. */
  kindCounts: Partial<Record<string, number>>;
};

export function isLayer(value: unknown): value is Layer {
  if (typeof value !== "object" || value === null) return false;
  const layer = value as Record<string, unknown>;
  return typeof layer.id === "string" && typeof layer.name === "string";
}
